---
- name: Instalar server azure
  hosts: ansible_host_vm 
  remote_user: ansible_host
  vars:
    ansible_ssh_private_key_file: "{{ hostvars[inventory_hostname]['ansible_ssh_private_key_file'] }}"
  become: true 

  tasks:
   - name: Actualizar repositorios apt
     apt:
        upgrade: dist
        update_cache: yes
   
   - name: Instalar Podman
     apt:
        name:
           - podman
        state: present